<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EMOO80V" failures="0" tests="8" name="com.dependencies.TestGroupDependent" time="0.118" errors="1" timestamp="2022-08-18T21:35:42 IST" skipped="5">
  <testcase classname="com.dependencies.TestGroupDependent" name="Test6" time="0.000">
    <skipped/>
  </testcase> <!-- Test6 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test7" time="0.004"/>
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test2" time="0.011">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.dependencies.TestGroupDependent.Test2(TestGroupDependent.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test2 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test4" time="0.000">
    <skipped/>
  </testcase> <!-- Test4 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test5" time="0.000">
    <skipped/>
  </testcase> <!-- Test5 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test3" time="0.000">
    <skipped/>
  </testcase> <!-- Test3 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test8" time="0.001">
    <skipped/>
  </testcase> <!-- Test8 -->
  <system-out/>
  <testcase classname="com.dependencies.TestGroupDependent" name="Test1" time="0.102"/>
  <system-out/>
</testsuite> <!-- com.dependencies.TestGroupDependent -->
